name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setting up Github Actions
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Installing Dependencies
        run: pip install -r requirements.txt

      - name: Building the Image
        run: make build_test

      - name: Configuring AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.UNIT_TESTS_AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.UNIT_TESTS_AWS_REGION }}
          aws-secret-access-key: ${{ secrets.UNIT_TESTS_AWS_SECRET_ACCESS_KEY }}

      - name: Building s3 bucket and uploading test data
        run: |
          python -m test.setup_tests ingest-unit-test-document-bucket ingest-unit-test-pipeline-bucket ${{ secrets.UNIT_TESTS_AWS_REGION }} ./test/data/docs_test_subset.json

      - name: Running the Ingest Stage
        run: |
          docker run -e AWS_ACCESS_KEY_ID=${{ secrets.UNIT_TESTS_AWS_ACCESS_KEY_ID }} -e AWS_SECRET_ACCESS_KEY=${{ secrets.UNIT_TESTS_AWS_SECRET_ACCESS_KEY }} -e API_HOST="" -e MACHINE_USER_EMAIL="" -e MACHINE_USER_PASSWORD=""  navigator-data-ingest-test --pipeline-bucket ingest_unit_test_pipeline_bucket --document-bucket ingest_unit_test_document_bucket --input-file input/docs_test_subset.json --output-prefix ingest_unit_test_parser_input --worker-count 1

      - name: Running Pytest on the Ingest Stage Output 🚀
        run: |
          python -m pytest

      - name: Destroying Infrastructure
        if: always()
        run: |
          python -m test.clean_up_tests ingest_unit_test_document_bucket ingest_unit_test_pipeline_bucket
