name: unit_tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setting up Github Actions
        uses: actions/checkout@v3

      - name: Setting up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Installing Dependencies
        run:
          poetry export --without-hashes --format=requirements.txt > requirements.txt
          pip install -r requirements.txt

      - name: Building the Image
        run: make build_test

      - name: Running Unit Tests of the Ingest Application
        run: | 
          make test